# Generated by Django 5.2.17 on 2026-08-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=7)),
                ("first_login", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=8, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
